chore: add eslint
asyncapi/nodejs-template pull request #123
Opened 2022-01-18 05:44 UTC by Krishks369

Added eslint template for ease of reading

2022-01-18 07:35 UTC, derberg requested changes
few fixes suggested

2022-01-18 07:35 UTC, derberg commented on filters/all.js
> +/* eslint-disable */
why do we need to disable here?

2022-01-18 07:35 UTC, derberg commented on filters/all.js
> +/* eslint-disable */
we could actually remove this filter and import it from here https://github.com/asyncapi/generator-filters/blob/master/src/customFilters.js as one guy took it one day to main filters package. You could basically just remove this function and all should work as `generator-filters` are configured here already.

please just run generation locally and test it as described in readme, to be 100% sure all works like a charm

2022-01-18 07:35 UTC, derberg commented on package.json
> +    "lint:fix": "eslint --fix --ext .js,.jsx .",
why not `eslint --fix --config .eslintrc .` ?

2022-01-18 14:46 UTC, Samridhi-98 reviewed
@derberg  @Krishks369  I would suggest adding `package.json` and 
`package-lock.json`  in `.eslintignore`  because no point to run lint on packages.

2022-01-18 15:33 UTC, derberg requested changes
cool!

what left is:
- my comment to `npm`. I guess it is not needed really, so remove and refresh `package-lock.json`
- extend description that `replaceVariablesWithValues` was removed and why
- indicate that you tested locally and communication from mqtt client to generated server was successful

2022-01-20 09:10 UTC, derberg approved these changes
Thanks 🚀 
Awesome contribution!!!

2022-01-20 09:51 UTC, derberg commented
/rtm

2022-01-20 09:53 UTC, merged